### ISSUE TITLE
[CDSToolkit] - Error while publishing throttling policy

### ISSUE THREAD

**Issue by malshaniS** [wso2/financial-services-accelerator#147]
**Description:**
Observed the below error while publishing throttling policy.

```
TID: [] [] [2024-10-16 03:25:42,049]  INFO {org.wso2.carbon.event.processor.core.internal.util.EventProcessorConfigurationFilesystemInvoker} - Execution plan: global_Unattended-SessionsPerDayPerCustomerPerDR saved in the filesystem
TID: [] [] [2024-10-16 03:25:42,054] ERROR {org.wso2.carbon.event.processor.core.EventProcessorDeployer} - Execution plan is not deployed and in inactive state : global_Unattended-SessionsPerDayPerCustomerPerDR.siddhiql org.wso2.carbon.event.processor.core.exception.ExecutionPlanConfigurationException: No extension exist for AttributeFunction{extensionName='eventtable', functionName='rdbms', parameters=[]}
	at org.wso2.carbon.event.processor.core.internal.util.helper.EventProcessorHelper.validateExecutionPlan(EventProcessorHelper.java:207)
	at org.wso2.carbon.event.processor.core.EventProcessorDeployer.processDeploy(EventProcessorDeployer.java:121)
	at org.wso2.carbon.event.processor.core.EventProcessorDeployer.executeManualDeployment(EventProcessorDeployer.java:178)
	at org.wso2.carbon.event.processor.core.internal.util.EventProcessorConfigurationFilesystemInvoker.save(EventProcessorConfigurationFilesystemInvoker.java:97)
	at org.wso2.carbon.event.processor.core.internal.CarbonEventProcessorService.deployExecutionPlan(CarbonEventProcessorService.java:114)
	at org.wso2.carbon.apimgt.throttle.policy.deployer.utils.PolicyUtil.deployPolicy(PolicyUtil.java:134)
	at org.wso2.carbon.apimgt.throttle.policy.deployer.utils.ThrottlePolicyJMSMessageListener.lambda$handleNotificationMessage$3(ThrottlePolicyJMSMessageListener.java:184)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.wso2.siddhi.core.exception.ExecutionPlanCreationException: No extension exist for AttributeFunction{extensionName='eventtable', functionName='rdbms', parameters=[]}
	at org.wso2.siddhi.core.util.SiddhiClassLoader.loadExtensionImplementation(SiddhiClassLoader.java:67)
	at org.wso2.siddhi.core.util.parser.helper.DefinitionParserHelper.addEventTable(DefinitionParserHelper.java:113)
	at org.wso2.siddhi.core.util.ExecutionPlanRuntimeBuilder.defineTable(ExecutionPlanRuntimeBuilder.java:85)
	at org.wso2.siddhi.core.util.parser.ExecutionPlanParser.defineTableDefinitions(ExecutionPlanParser.java:267)
	at org.wso2.siddhi.core.util.parser.ExecutionPlanParser.parse(ExecutionPlanParser.java:192)
	at org.wso2.siddhi.core.SiddhiManager.validateExecutionPlan(SiddhiManager.java:94)
	at org.wso2.siddhi.core.SiddhiManager.validateExecutionPlan(SiddhiManager.java:106)
	at org.wso2.carbon.event.processor.core.internal.util.helper.EventProcessorHelper.validateExecutionPlan(EventProcessorHelper.java:205)
	... 12 more

TID: [] [] [2024-10-16 03:25:42,054] ERROR {org.wso2.carbon.apimgt.throttle.policy.deployer.utils.PolicyUtil} - Error in deploying execution plan org.wso2.carbon.event.processor.core.exception.ExecutionPlanConfigurationException: No extension exist for AttributeFunction{extensionName='eventtable', functionName='rdbms', parameters=[]}
	at org.wso2.carbon.event.processor.core.EventProcessorDeployer.processDeploy(EventProcessorDeployer.java:154)
	at org.wso2.carbon.event.processor.core.EventProcessorDeployer.executeManualDeployment(EventProcessorDeployer.java:178)
	at org.wso2.carbon.event.processor.core.internal.util.EventProcessorConfigurationFilesystemInvoker.save(EventProcessorConfigurationFilesystemInvoker.java:97)
	at org.wso2.carbon.event.processor.core.internal.CarbonEventProcessorService.deployExecutionPlan(CarbonEventProcessorService.java:114)
	at org.wso2.carbon.apimgt.throttle.policy.deployer.utils.PolicyUtil.deployPolicy(PolicyUtil.java:134)
	at org.wso2.carbon.apimgt.throttle.policy.deployer.utils.ThrottlePolicyJMSMessageListener.lambda$handleNotificationMessage$3(ThrottlePolicyJMSMessageListener.java:184)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.wso2.carbon.event.processor.core.exception.ExecutionPlanConfigurationException: No extension exist for AttributeFunction{extensionName='eventtable', functionName='rdbms', parameters=[]}
	at org.wso2.carbon.event.processor.core.internal.util.helper.EventProcessorHelper.validateExecutionPlan(EventProcessorHelper.java:207)
	at org.wso2.carbon.event.processor.core.EventProcessorDeployer.processDeploy(EventProcessorDeployer.java:121)
	... 11 more
Caused by: org.wso2.siddhi.core.exception.ExecutionPlanCreationException: No extension exist for AttributeFunction{extensionName='eventtable', functionName='rdbms', parameters=[]}
	at org.wso2.siddhi.core.util.SiddhiClassLoader.loadExtensionImplementation(SiddhiClassLoader.java:67)
	at org.wso2.siddhi.core.util.parser.helper.DefinitionParserHelper.addEventTable(DefinitionParserHelper.java:113)
	at org.wso2.siddhi.core.util.ExecutionPlanRuntimeBuilder.defineTable(ExecutionPlanRuntimeBuilder.java:85)
	at org.wso2.siddhi.core.util.parser.ExecutionPlanParser.defineTableDefinitions(ExecutionPlanParser.java:267)
	at org.wso2.siddhi.core.util.parser.ExecutionPlanParser.parse(ExecutionPlanParser.java:192)
	at org.wso2.siddhi.core.SiddhiManager.validateExecutionPlan(SiddhiManager.java:94)
	at org.wso2.siddhi.core.SiddhiManager.validateExecutionPlan(SiddhiManager.java:106)
	at org.wso2.carbon.event.processor.core.internal.util.helper.EventProcessorHelper.validateExecutionPlan(EventProcessorHelper.java:205)
```

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**

**Steps to reproduce:**
1. Publish "Unattended-SessionsPerDayPerCustomerPerDR" policy and verify the log

**Related Issues:**
[Any related issues such as sub tasks, issues reported in other repositories (e.g component repositories), similar problems, etc. ]

**Comment by imesh94** [comment]
Cannot be reproduced in the latest packs.

**Comment by malshaniS** [comment]
This error is fixed in latest pack.

**Comment by malshaniS** [comment]
Closing the issue as this is occurred due to an error while copying the siddhi code when publishing the throttling policy.
